# Generated by Django 5.2.5 on 2025-08-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0002_client_city_client_country_client_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(default='hours', help_text='Unit of measurement (e.g., hours, pieces, days, kg)', max_length=50),
        ),
    ]
